name: Atualizar Tabela Diaria

on:
  schedule:
    # Roda todos os dias às 11:00 UTC (que equivale às 08:00 no horário de Brasília)
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite que você rode o robô manualmente apertando um botão no GitHub se quiser

jobs:
  baixar_e_processar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Bibliotecas
        run: |
          pip install -r requirements.txt

      - name: Rodar o Robô
        run: python robo.py

      - name: Salvar a Nova Tabela no GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tabela_do_dia.xlsx
          # Se não houver alteração (fim de semana por ex), ele não dá erro
          git commit -m "Atualização diária da tabela" || echo "Sem mudanças para commitar"
          git push
