name: Atualizar Tabela Diaria

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Essa linha é a chave para acabar com o erro 403

jobs:
  baixar_e_processar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Bibliotecas
        run: |
          pip install requests pandas openpyxl

      - name: Rodar o Robô
        run: python robo.py

      - name: Salvar a Nova Tabela no GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tabela_do_dia.xlsx
          git commit -m "Atualização diária da tabela" || echo "Sem mudanças"
          git push
